apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: install-mcg-noobaa
policyDefaults:
  namespace: policies
  remediationAction: enforce
  placement:
    labelSelector:
      matchExpressions:
        - key: vendor
          operator: In
          values:
            - "OpenShift"
policies:
  - name: install-mcg-operator
    manifests:
      - path: manifests/mcg-operator.yaml
  - name: install-noobaa
    dependencies:
      - name: install-mcg-operator
    manifests:
      - path: manifests/noobaa.yaml
