apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: create-loki-bucket-secret
spec:
  remediationAction: enforce
  severity: medium
  object-templates-raw: |
    {{- $cm := (lookup "v1" "ConfigMap" "openshift-logging" "loki-bucket-odf") }}
    {{- $secret := (lookup "v1" "Secret" "openshift-logging" "loki-bucket-odf") }}
    {{- if and $cm $secret }}
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: Secret
        metadata:
          name: logging-loki-odf
          namespace: openshift-logging
        type: Opaque
        stringData:
          access_key_id: {{ index $secret.data "AWS_ACCESS_KEY_ID" | base64dec }}
          access_key_secret: {{ index $secret.data "AWS_SECRET_ACCESS_KEY" | base64dec }}
          bucketnames: {{ $cm.data.BUCKET_NAME }}
          endpoint: https://{{ $cm.data.BUCKET_HOST }}:{{ $cm.data.BUCKET_PORT }}
    {{- end }}
