apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: testapp-threepilars
  namespace: testapp-threepilars
spec:
  generators:
  - clusterDecisionResource:
      configMapRef: acm-placement
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: testapp-clusters
      requeueAfterSeconds: 180
  template:
    metadata:
      annotations:
        apps.open-cluster-management.io/ocm-managed-cluster: '{{name}}'
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true"
      name: '{{name}}-testapp-threepilars'
    spec:
      destination:
        namespace: testapp-threepilars-app
        server: https://kubernetes.default.svc
      project: default
      source:
        path: 04_Testapp-threepilars
        repoURL: https://github.com/nigsmith/testapp-threepilars-ACM.git
        targetRevision: main
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true
