apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: PR.PT Protective Technology
    policy.open-cluster-management.io/controls: PR.PT-3 Least Functionality
    policy.open-cluster-management.io/standards: NIST-CSF
  name: argo-acm-importer-argocd-policy
  namespace: openshift-gitops
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: argo-acm-importer-argocd-config-policy
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: argoproj.io/v1beta1
            kind: ArgoCD
            metadata:
              labels:
                apps.open-cluster-management.io/gitopsaddon: "true"
              name: acm-openshift-gitops
              namespace: openshift-gitops
            spec:
              controller:
                enabled: true
                env:
                - name: ARGOCD_APPLICATION_NAMESPACES
                  value: '*'
              server:
                enabled: false
        - complianceType: musthave
          objectDefinition:
            apiVersion: argoproj.io/v1alpha1
            kind: AppProject
            metadata:
              name: default
              namespace: openshift-gitops
            spec:
              clusterResourceWhitelist:
              - group: '*'
                kind: '*'
              destinations:
              - namespace: '*'
                server: '*'
              sourceRepos:
              - '*'
              sourceNamespaces:
              - '*'
        - complianceType: musthave
          objectDefinition:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRoleBinding
            metadata:
              name: argo-admin
            subjects:
              - kind: ServiceAccount
                name: acm-openshift-gitops-argocd-application-controller
                namespace: openshift-gitops
            roleRef:
              apiGroup: rbac.authorization.k8s.io
              kind: ClusterRole
              name: cluster-admin
        pruneObjectBehavior: None
        remediationAction: enforce
        severity: medium
  remediationAction: enforce
